//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltHealth.Data.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HealthEntities : DbContext
    {
        public HealthEntities()
            : base("name=HealthEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblClientInfo> tblClientInfoes { get; set; }
        public virtual DbSet<tblInv_Info> tblInv_Info { get; set; }
        public virtual DbSet<tblInv_items> tblInv_items { get; set; }
        public virtual DbSet<tblReference> tblReferences { get; set; }
        public virtual DbSet<tblSupplement> tblSupplements { get; set; }
        public virtual DbSet<tblSupplier_info> tblSupplier_info { get; set; }
    
        public virtual ObjectResult<string> spGenerateInvoiceNumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spGenerateInvoiceNumber");
        }
    
        public virtual ObjectResult<spGetBirthDays_Result> spGetBirthDays()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetBirthDays_Result>("spGetBirthDays");
        }
    
        public virtual ObjectResult<spGetCartItems_Result> spGetCartItems(string invoiceNo, string clientID)
        {
            var invoiceNoParameter = invoiceNo != null ?
                new ObjectParameter("InvoiceNo", invoiceNo) :
                new ObjectParameter("InvoiceNo", typeof(string));
    
            var clientIDParameter = clientID != null ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCartItems_Result>("spGetCartItems", invoiceNoParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<spGetClients_Result> spGetClients(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetClients_Result>("spGetClients", searchParameter);
        }
    
        public virtual ObjectResult<spGetSuppliers_Result> spGetSuppliers(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSuppliers_Result>("spGetSuppliers", searchParameter);
        }
    
        public virtual ObjectResult<spGetSuppliments_Result> spGetSuppliments(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSuppliments_Result>("spGetSuppliments", searchParameter);
        }
    
        public virtual ObjectResult<spGetTopTenClients_Result> spGetTopTenClients()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetTopTenClients_Result>("spGetTopTenClients");
        }
    
        public virtual ObjectResult<spGetUnpaidInvoices_Result> spGetUnpaidInvoices()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetUnpaidInvoices_Result>("spGetUnpaidInvoices");
        }
    
        public virtual ObjectResult<spGetStockLevels_Result> spGetStockLevels()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetStockLevels_Result>("spGetStockLevels");
        }
    
        public virtual ObjectResult<spGetPurchaseStats_Result> spGetPurchaseStats(Nullable<int> startYear)
        {
            var startYearParameter = startYear.HasValue ?
                new ObjectParameter("StartYear", startYear) :
                new ObjectParameter("StartYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetPurchaseStats_Result>("spGetPurchaseStats", startYearParameter);
        }
    
        public virtual ObjectResult<spGetClientsWithNoEmails_Result> spGetClientsWithNoEmails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetClientsWithNoEmails_Result>("spGetClientsWithNoEmails");
        }
    
        public virtual ObjectResult<spGetInvoices_Result> spGetInvoices(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetInvoices_Result>("spGetInvoices", searchParameter);
        }
    }
}
