//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltHealth.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInv_items
    {
        public decimal Item_Price { get; set; }
        public int Item_Quantity { get; set; }
        public string Supplement_id { get; set; }
        public string Inv_Num { get; set; }
    
        public virtual tblInv_Info tblInv_Info { get; set; }
        public virtual tblSupplement tblSupplement { get; set; }
    }
}
