//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltHealth.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInv_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInv_Info()
        {
            this.tblInv_items = new HashSet<tblInv_items>();
        }
    
        public string Inv_Num { get; set; }
        public System.DateTime Inv_Date { get; set; }
        public bool Inv_Paid { get; set; }
        public Nullable<System.DateTime> Inv_Paid_Date { get; set; }
        public string Comments { get; set; }
        public string Client_id { get; set; }
    
        public virtual tblClientInfo tblClientInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInv_items> tblInv_items { get; set; }
    }
}
