//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltHealth.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSupplement()
        {
            this.tblInv_items = new HashSet<tblInv_items>();
        }
    
        public string Supplement_id { get; set; }
        public string Supplement_Description { get; set; }
        public decimal Cost_excl { get; set; }
        public decimal Cost_incl { get; set; }
        public int Min_Level { get; set; }
        public int Current_Stock_Levels { get; set; }
        public string Nappi_code { get; set; }
        public string Supplier_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInv_items> tblInv_items { get; set; }
        public virtual tblSupplier_info tblSupplier_info { get; set; }
    }
}
