//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltHealth.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplier_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSupplier_info()
        {
            this.tblSupplements = new HashSet<tblSupplement>();
        }
    
        public string Supplier_Id { get; set; }
        public string Contact_Person { get; set; }
        public string Supplier_Tel { get; set; }
        public string Supplier_Email { get; set; }
        public string Bank { get; set; }
        public string Bank_Code { get; set; }
        public string Supplier_BankNum { get; set; }
        public string Supplier_Type_Bank_Annount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupplement> tblSupplements { get; set; }
    }
}
